//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfratProject.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="customers", Namespace="http://schemas.datacontract.org/2004/07/ServerProject.BLL")]
    [System.SerializableAttribute()]
    public partial class customers : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeCustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string adressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EfratProject.ServiceReference2.Cities city1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string floorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int housField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodeCustomer {
            get {
                return this.CodeCustomerField;
            }
            set {
                if ((this.CodeCustomerField.Equals(value) != true)) {
                    this.CodeCustomerField = value;
                    this.RaisePropertyChanged("CodeCustomer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string adress {
            get {
                return this.adressField;
            }
            set {
                if ((object.ReferenceEquals(this.adressField, value) != true)) {
                    this.adressField = value;
                    this.RaisePropertyChanged("adress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apartment {
            get {
                return this.apartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.apartmentField, value) != true)) {
                    this.apartmentField = value;
                    this.RaisePropertyChanged("apartment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EfratProject.ServiceReference2.Cities city1 {
            get {
                return this.city1Field;
            }
            set {
                if ((object.ReferenceEquals(this.city1Field, value) != true)) {
                    this.city1Field = value;
                    this.RaisePropertyChanged("city1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string floor {
            get {
                return this.floorField;
            }
            set {
                if ((object.ReferenceEquals(this.floorField, value) != true)) {
                    this.floorField = value;
                    this.RaisePropertyChanged("floor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int hous {
            get {
                return this.housField;
            }
            set {
                if ((this.housField.Equals(value) != true)) {
                    this.housField = value;
                    this.RaisePropertyChanged("hous");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mail {
            get {
                return this.mailField;
            }
            set {
                if ((object.ReferenceEquals(this.mailField, value) != true)) {
                    this.mailField = value;
                    this.RaisePropertyChanged("mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneField, value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cities", Namespace="http://schemas.datacontract.org/2004/07/ServerProject.BLL")]
    [System.SerializableAttribute()]
    public partial class Cities : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CityCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DayInWeekField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CityCode {
            get {
                return this.CityCodeField;
            }
            set {
                if ((this.CityCodeField.Equals(value) != true)) {
                    this.CityCodeField = value;
                    this.RaisePropertyChanged("CityCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityName {
            get {
                return this.CityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CityNameField, value) != true)) {
                    this.CityNameField = value;
                    this.RaisePropertyChanged("CityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DayInWeek {
            get {
                return this.DayInWeekField;
            }
            set {
                if ((this.DayInWeekField.Equals(value) != true)) {
                    this.DayInWeekField = value;
                    this.RaisePropertyChanged("DayInWeek");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Inviting", Namespace="http://schemas.datacontract.org/2004/07/ServerProject.BLL")]
    [System.SerializableAttribute()]
    public partial class Inviting : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EfratProject.ServiceReference2.customers CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HazmanaCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateBuyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateSentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> filnalPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string notesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool sentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EfratProject.ServiceReference2.customers Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HazmanaCode {
            get {
                return this.HazmanaCodeField;
            }
            set {
                if ((this.HazmanaCodeField.Equals(value) != true)) {
                    this.HazmanaCodeField = value;
                    this.RaisePropertyChanged("HazmanaCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateBuy {
            get {
                return this.dateBuyField;
            }
            set {
                if ((this.dateBuyField.Equals(value) != true)) {
                    this.dateBuyField = value;
                    this.RaisePropertyChanged("dateBuy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateSent {
            get {
                return this.dateSentField;
            }
            set {
                if ((this.dateSentField.Equals(value) != true)) {
                    this.dateSentField = value;
                    this.RaisePropertyChanged("dateSent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> filnalPrice {
            get {
                return this.filnalPriceField;
            }
            set {
                if ((this.filnalPriceField.Equals(value) != true)) {
                    this.filnalPriceField = value;
                    this.RaisePropertyChanged("filnalPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string notes {
            get {
                return this.notesField;
            }
            set {
                if ((object.ReferenceEquals(this.notesField, value) != true)) {
                    this.notesField = value;
                    this.RaisePropertyChanged("notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool sent {
            get {
                return this.sentField;
            }
            set {
                if ((this.sentField.Equals(value) != true)) {
                    this.sentField = value;
                    this.RaisePropertyChanged("sent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BlProduct", Namespace="http://schemas.datacontract.org/2004/07/ServerProject.BLL")]
    [System.SerializableAttribute()]
    public partial class BlProduct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> AmountInField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EfratProject.ServiceReference2.kategor KategorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EfratProject.ServiceReference2.kosher KosherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool tariField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> AmountIn {
            get {
                return this.AmountInField;
            }
            set {
                if ((this.AmountInField.Equals(value) != true)) {
                    this.AmountInField = value;
                    this.RaisePropertyChanged("AmountIn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EfratProject.ServiceReference2.kategor Kategor {
            get {
                return this.KategorField;
            }
            set {
                if ((object.ReferenceEquals(this.KategorField, value) != true)) {
                    this.KategorField = value;
                    this.RaisePropertyChanged("Kategor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EfratProject.ServiceReference2.kosher Kosher {
            get {
                return this.KosherField;
            }
            set {
                if ((object.ReferenceEquals(this.KosherField, value) != true)) {
                    this.KosherField = value;
                    this.RaisePropertyChanged("Kosher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductCode {
            get {
                return this.ProductCodeField;
            }
            set {
                if ((this.ProductCodeField.Equals(value) != true)) {
                    this.ProductCodeField = value;
                    this.RaisePropertyChanged("ProductCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string picture {
            get {
                return this.pictureField;
            }
            set {
                if ((object.ReferenceEquals(this.pictureField, value) != true)) {
                    this.pictureField = value;
                    this.RaisePropertyChanged("picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool tari {
            get {
                return this.tariField;
            }
            set {
                if ((this.tariField.Equals(value) != true)) {
                    this.tariField = value;
                    this.RaisePropertyChanged("tari");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="kategor", Namespace="http://schemas.datacontract.org/2004/07/ServerProject.BLL")]
    [System.SerializableAttribute()]
    public partial class kategor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KategorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KategorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] KategorPictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<EfratProject.ServiceReference2.BlProduct> productsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KategorCode {
            get {
                return this.KategorCodeField;
            }
            set {
                if ((this.KategorCodeField.Equals(value) != true)) {
                    this.KategorCodeField = value;
                    this.RaisePropertyChanged("KategorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KategorName {
            get {
                return this.KategorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.KategorNameField, value) != true)) {
                    this.KategorNameField = value;
                    this.RaisePropertyChanged("KategorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] KategorPicture {
            get {
                return this.KategorPictureField;
            }
            set {
                if ((object.ReferenceEquals(this.KategorPictureField, value) != true)) {
                    this.KategorPictureField = value;
                    this.RaisePropertyChanged("KategorPicture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<EfratProject.ServiceReference2.BlProduct> products {
            get {
                return this.productsField;
            }
            set {
                if ((object.ReferenceEquals(this.productsField, value) != true)) {
                    this.productsField = value;
                    this.RaisePropertyChanged("products");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="kosher", Namespace="http://schemas.datacontract.org/2004/07/ServerProject.BLL")]
    [System.SerializableAttribute()]
    public partial class kosher : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KosherCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KosherNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] KosherPictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<EfratProject.ServiceReference2.BlProduct> productsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KosherCode {
            get {
                return this.KosherCodeField;
            }
            set {
                if ((this.KosherCodeField.Equals(value) != true)) {
                    this.KosherCodeField = value;
                    this.RaisePropertyChanged("KosherCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KosherName {
            get {
                return this.KosherNameField;
            }
            set {
                if ((object.ReferenceEquals(this.KosherNameField, value) != true)) {
                    this.KosherNameField = value;
                    this.RaisePropertyChanged("KosherName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] KosherPicture {
            get {
                return this.KosherPictureField;
            }
            set {
                if ((object.ReferenceEquals(this.KosherPictureField, value) != true)) {
                    this.KosherPictureField = value;
                    this.RaisePropertyChanged("KosherPicture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<EfratProject.ServiceReference2.BlProduct> products {
            get {
                return this.productsField;
            }
            set {
                if ((object.ReferenceEquals(this.productsField, value) != true)) {
                    this.productsField = value;
                    this.RaisePropertyChanged("products");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="hazmana", Namespace="http://schemas.datacontract.org/2004/07/ServerProject.BLL")]
    [System.SerializableAttribute()]
    public partial class hazmana : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EfratProject.ServiceReference2.Inviting invitingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EfratProject.ServiceReference2.BlProduct productField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool sentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EfratProject.ServiceReference2.Inviting inviting {
            get {
                return this.invitingField;
            }
            set {
                if ((object.ReferenceEquals(this.invitingField, value) != true)) {
                    this.invitingField = value;
                    this.RaisePropertyChanged("inviting");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EfratProject.ServiceReference2.BlProduct product {
            get {
                return this.productField;
            }
            set {
                if ((object.ReferenceEquals(this.productField, value) != true)) {
                    this.productField = value;
                    this.RaisePropertyChanged("product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool sent {
            get {
                return this.sentField;
            }
            set {
                if ((this.sentField.Equals(value) != true)) {
                    this.sentField = value;
                    this.RaisePropertyChanged("sent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsPasswordCorrect", ReplyAction="http://tempuri.org/IService1/IsPasswordCorrectResponse")]
        bool IsPasswordCorrect(string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsPasswordCorrect", ReplyAction="http://tempuri.org/IService1/IsPasswordCorrectResponse")]
        System.Threading.Tasks.Task<bool> IsPasswordCorrectAsync(string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChangePassword", ReplyAction="http://tempuri.org/IService1/ChangePasswordResponse")]
        bool ChangePassword(string newPassword, string oldPassward);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChangePassword", ReplyAction="http://tempuri.org/IService1/ChangePasswordResponse")]
        System.Threading.Tasks.Task<bool> ChangePasswordAsync(string newPassword, string oldPassward);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AmountCustomers", ReplyAction="http://tempuri.org/IService1/AmountCustomersResponse")]
        int AmountCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AmountCustomers", ReplyAction="http://tempuri.org/IService1/AmountCustomersResponse")]
        System.Threading.Tasks.Task<int> AmountCustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomers", ReplyAction="http://tempuri.org/IService1/GetCustomersResponse")]
        System.Collections.Generic.List<EfratProject.ServiceReference2.customers> GetCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomers", ReplyAction="http://tempuri.org/IService1/GetCustomersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<EfratProject.ServiceReference2.customers>> GetCustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInvitings", ReplyAction="http://tempuri.org/IService1/GetInvitingsResponse")]
        System.Collections.Generic.List<EfratProject.ServiceReference2.Inviting> GetInvitings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInvitings", ReplyAction="http://tempuri.org/IService1/GetInvitingsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<EfratProject.ServiceReference2.Inviting>> GetInvitingsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCustomers", ReplyAction="http://tempuri.org/IService1/AddCustomersResponse")]
        bool AddCustomers(EfratProject.ServiceReference2.customers c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCustomers", ReplyAction="http://tempuri.org/IService1/AddCustomersResponse")]
        System.Threading.Tasks.Task<bool> AddCustomersAsync(EfratProject.ServiceReference2.customers c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomerByPhone", ReplyAction="http://tempuri.org/IService1/GetCustomerByPhoneResponse")]
        EfratProject.ServiceReference2.customers GetCustomerByPhone(string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomerByPhone", ReplyAction="http://tempuri.org/IService1/GetCustomerByPhoneResponse")]
        System.Threading.Tasks.Task<EfratProject.ServiceReference2.customers> GetCustomerByPhoneAsync(string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCity", ReplyAction="http://tempuri.org/IService1/GetCityResponse")]
        System.Collections.Generic.List<EfratProject.ServiceReference2.Cities> GetCity();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCity", ReplyAction="http://tempuri.org/IService1/GetCityResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<EfratProject.ServiceReference2.Cities>> GetCityAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCustomer", ReplyAction="http://tempuri.org/IService1/UpdateCustomerResponse")]
        bool UpdateCustomer(EfratProject.ServiceReference2.customers c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCustomer", ReplyAction="http://tempuri.org/IService1/UpdateCustomerResponse")]
        System.Threading.Tasks.Task<bool> UpdateCustomerAsync(EfratProject.ServiceReference2.customers c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCity", ReplyAction="http://tempuri.org/IService1/UpdateCityResponse")]
        bool UpdateCity(EfratProject.ServiceReference2.Cities C);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCity", ReplyAction="http://tempuri.org/IService1/UpdateCityResponse")]
        System.Threading.Tasks.Task<bool> UpdateCityAsync(EfratProject.ServiceReference2.Cities C);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateProduct", ReplyAction="http://tempuri.org/IService1/UpdateProductResponse")]
        bool UpdateProduct(EfratProject.ServiceReference2.BlProduct p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateProduct", ReplyAction="http://tempuri.org/IService1/UpdateProductResponse")]
        System.Threading.Tasks.Task<bool> UpdateProductAsync(EfratProject.ServiceReference2.BlProduct p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateKosher", ReplyAction="http://tempuri.org/IService1/UpdateKosherResponse")]
        bool UpdateKosher(EfratProject.ServiceReference2.kosher kosh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateKosher", ReplyAction="http://tempuri.org/IService1/UpdateKosherResponse")]
        System.Threading.Tasks.Task<bool> UpdateKosherAsync(EfratProject.ServiceReference2.kosher kosh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProduct", ReplyAction="http://tempuri.org/IService1/AddProductResponse")]
        bool AddProduct(EfratProject.ServiceReference2.BlProduct p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProduct", ReplyAction="http://tempuri.org/IService1/AddProductResponse")]
        System.Threading.Tasks.Task<bool> AddProductAsync(EfratProject.ServiceReference2.BlProduct p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProducts", ReplyAction="http://tempuri.org/IService1/GetProductsResponse")]
        System.Collections.Generic.List<EfratProject.ServiceReference2.BlProduct> GetProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProducts", ReplyAction="http://tempuri.org/IService1/GetProductsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<EfratProject.ServiceReference2.BlProduct>> GetProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetKosher", ReplyAction="http://tempuri.org/IService1/GetKosherResponse")]
        System.Collections.Generic.List<EfratProject.ServiceReference2.kosher> GetKosher();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetKosher", ReplyAction="http://tempuri.org/IService1/GetKosherResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<EfratProject.ServiceReference2.kosher>> GetKosherAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddKosher", ReplyAction="http://tempuri.org/IService1/AddKosherResponse")]
        bool AddKosher(EfratProject.ServiceReference2.kosher k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddKosher", ReplyAction="http://tempuri.org/IService1/AddKosherResponse")]
        System.Threading.Tasks.Task<bool> AddKosherAsync(EfratProject.ServiceReference2.kosher k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetKategor", ReplyAction="http://tempuri.org/IService1/GetKategorResponse")]
        System.Collections.Generic.List<EfratProject.ServiceReference2.kategor> GetKategor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetKategor", ReplyAction="http://tempuri.org/IService1/GetKategorResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<EfratProject.ServiceReference2.kategor>> GetKategorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInviting", ReplyAction="http://tempuri.org/IService1/GetInvitingResponse")]
        System.Collections.Generic.List<EfratProject.ServiceReference2.Inviting> GetInviting();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInviting", ReplyAction="http://tempuri.org/IService1/GetInvitingResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<EfratProject.ServiceReference2.Inviting>> GetInvitingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCity", ReplyAction="http://tempuri.org/IService1/AddCityResponse")]
        bool AddCity(EfratProject.ServiceReference2.Cities c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCity", ReplyAction="http://tempuri.org/IService1/AddCityResponse")]
        System.Threading.Tasks.Task<bool> AddCityAsync(EfratProject.ServiceReference2.Cities c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteproduct", ReplyAction="http://tempuri.org/IService1/deleteproductResponse")]
        bool deleteproduct(EfratProject.ServiceReference2.BlProduct p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteproduct", ReplyAction="http://tempuri.org/IService1/deleteproductResponse")]
        System.Threading.Tasks.Task<bool> deleteproductAsync(EfratProject.ServiceReference2.BlProduct p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteCity", ReplyAction="http://tempuri.org/IService1/deleteCityResponse")]
        bool deleteCity(EfratProject.ServiceReference2.Cities c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteCity", ReplyAction="http://tempuri.org/IService1/deleteCityResponse")]
        System.Threading.Tasks.Task<bool> deleteCityAsync(EfratProject.ServiceReference2.Cities c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteCustomer", ReplyAction="http://tempuri.org/IService1/deleteCustomerResponse")]
        bool deleteCustomer(EfratProject.ServiceReference2.customers c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteCustomer", ReplyAction="http://tempuri.org/IService1/deleteCustomerResponse")]
        System.Threading.Tasks.Task<bool> deleteCustomerAsync(EfratProject.ServiceReference2.customers c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteKosher", ReplyAction="http://tempuri.org/IService1/deleteKosherResponse")]
        bool deleteKosher(EfratProject.ServiceReference2.kosher kosh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteKosher", ReplyAction="http://tempuri.org/IService1/deleteKosherResponse")]
        System.Threading.Tasks.Task<bool> deleteKosherAsync(EfratProject.ServiceReference2.kosher kosh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteHazmana", ReplyAction="http://tempuri.org/IService1/deleteHazmanaResponse")]
        bool deleteHazmana(EfratProject.ServiceReference2.Inviting I);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteHazmana", ReplyAction="http://tempuri.org/IService1/deleteHazmanaResponse")]
        System.Threading.Tasks.Task<bool> deleteHazmanaAsync(EfratProject.ServiceReference2.Inviting I);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetImage", ReplyAction="http://tempuri.org/IService1/GetImageResponse")]
        byte[] GetImage(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetImage", ReplyAction="http://tempuri.org/IService1/GetImageResponse")]
        System.Threading.Tasks.Task<byte[]> GetImageAsync(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveImage", ReplyAction="http://tempuri.org/IService1/SaveImageResponse")]
        void SaveImage(byte[] imageArray, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveImage", ReplyAction="http://tempuri.org/IService1/SaveImageResponse")]
        System.Threading.Tasks.Task SaveImageAsync(byte[] imageArray, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateOrder", ReplyAction="http://tempuri.org/IService1/CreateOrderResponse")]
        bool CreateOrder(EfratProject.ServiceReference2.Inviting invite, System.Collections.Generic.List<EfratProject.ServiceReference2.hazmana> LProducts);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateOrder", ReplyAction="http://tempuri.org/IService1/CreateOrderResponse")]
        System.Threading.Tasks.Task<bool> CreateOrderAsync(EfratProject.ServiceReference2.Inviting invite, System.Collections.Generic.List<EfratProject.ServiceReference2.hazmana> LProducts);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchProducts", ReplyAction="http://tempuri.org/IService1/SearchProductsResponse")]
        System.Collections.Generic.List<EfratProject.ServiceReference2.BlProduct> SearchProducts(string P);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchProducts", ReplyAction="http://tempuri.org/IService1/SearchProductsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<EfratProject.ServiceReference2.BlProduct>> SearchProductsAsync(string P);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetproductBychoose", ReplyAction="http://tempuri.org/IService1/GetproductBychooseResponse")]
        System.Collections.Generic.List<EfratProject.ServiceReference2.BlProduct> GetproductBychoose(EfratProject.ServiceReference2.kategor w);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetproductBychoose", ReplyAction="http://tempuri.org/IService1/GetproductBychooseResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<EfratProject.ServiceReference2.BlProduct>> GetproductBychooseAsync(EfratProject.ServiceReference2.kategor w);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetItemsinOrder", ReplyAction="http://tempuri.org/IService1/GetItemsinOrderResponse")]
        System.Collections.Generic.List<EfratProject.ServiceReference2.hazmana> GetItemsinOrder();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetItemsinOrder", ReplyAction="http://tempuri.org/IService1/GetItemsinOrderResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<EfratProject.ServiceReference2.hazmana>> GetItemsinOrderAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveProductFromInvite", ReplyAction="http://tempuri.org/IService1/RemoveProductFromInviteResponse")]
        bool RemoveProductFromInvite(EfratProject.ServiceReference2.hazmana p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveProductFromInvite", ReplyAction="http://tempuri.org/IService1/RemoveProductFromInviteResponse")]
        System.Threading.Tasks.Task<bool> RemoveProductFromInviteAsync(EfratProject.ServiceReference2.hazmana p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrdersByCity", ReplyAction="http://tempuri.org/IService1/GetOrdersByCityResponse")]
        System.Collections.Generic.List<EfratProject.ServiceReference2.Inviting> GetOrdersByCity(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrdersByCity", ReplyAction="http://tempuri.org/IService1/GetOrdersByCityResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<EfratProject.ServiceReference2.Inviting>> GetOrdersByCityAsync(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrdersByDay", ReplyAction="http://tempuri.org/IService1/GetOrdersByDayResponse")]
        System.Collections.Generic.List<EfratProject.ServiceReference2.Inviting> GetOrdersByDay();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrdersByDay", ReplyAction="http://tempuri.org/IService1/GetOrdersByDayResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<EfratProject.ServiceReference2.Inviting>> GetOrdersByDayAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : EfratProject.ServiceReference2.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<EfratProject.ServiceReference2.IService1>, EfratProject.ServiceReference2.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IsPasswordCorrect(string password) {
            return base.Channel.IsPasswordCorrect(password);
        }
        
        public System.Threading.Tasks.Task<bool> IsPasswordCorrectAsync(string password) {
            return base.Channel.IsPasswordCorrectAsync(password);
        }
        
        public bool ChangePassword(string newPassword, string oldPassward) {
            return base.Channel.ChangePassword(newPassword, oldPassward);
        }
        
        public System.Threading.Tasks.Task<bool> ChangePasswordAsync(string newPassword, string oldPassward) {
            return base.Channel.ChangePasswordAsync(newPassword, oldPassward);
        }
        
        public int AmountCustomers() {
            return base.Channel.AmountCustomers();
        }
        
        public System.Threading.Tasks.Task<int> AmountCustomersAsync() {
            return base.Channel.AmountCustomersAsync();
        }
        
        public System.Collections.Generic.List<EfratProject.ServiceReference2.customers> GetCustomers() {
            return base.Channel.GetCustomers();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<EfratProject.ServiceReference2.customers>> GetCustomersAsync() {
            return base.Channel.GetCustomersAsync();
        }
        
        public System.Collections.Generic.List<EfratProject.ServiceReference2.Inviting> GetInvitings() {
            return base.Channel.GetInvitings();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<EfratProject.ServiceReference2.Inviting>> GetInvitingsAsync() {
            return base.Channel.GetInvitingsAsync();
        }
        
        public bool AddCustomers(EfratProject.ServiceReference2.customers c) {
            return base.Channel.AddCustomers(c);
        }
        
        public System.Threading.Tasks.Task<bool> AddCustomersAsync(EfratProject.ServiceReference2.customers c) {
            return base.Channel.AddCustomersAsync(c);
        }
        
        public EfratProject.ServiceReference2.customers GetCustomerByPhone(string phone) {
            return base.Channel.GetCustomerByPhone(phone);
        }
        
        public System.Threading.Tasks.Task<EfratProject.ServiceReference2.customers> GetCustomerByPhoneAsync(string phone) {
            return base.Channel.GetCustomerByPhoneAsync(phone);
        }
        
        public System.Collections.Generic.List<EfratProject.ServiceReference2.Cities> GetCity() {
            return base.Channel.GetCity();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<EfratProject.ServiceReference2.Cities>> GetCityAsync() {
            return base.Channel.GetCityAsync();
        }
        
        public bool UpdateCustomer(EfratProject.ServiceReference2.customers c) {
            return base.Channel.UpdateCustomer(c);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateCustomerAsync(EfratProject.ServiceReference2.customers c) {
            return base.Channel.UpdateCustomerAsync(c);
        }
        
        public bool UpdateCity(EfratProject.ServiceReference2.Cities C) {
            return base.Channel.UpdateCity(C);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateCityAsync(EfratProject.ServiceReference2.Cities C) {
            return base.Channel.UpdateCityAsync(C);
        }
        
        public bool UpdateProduct(EfratProject.ServiceReference2.BlProduct p) {
            return base.Channel.UpdateProduct(p);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateProductAsync(EfratProject.ServiceReference2.BlProduct p) {
            return base.Channel.UpdateProductAsync(p);
        }
        
        public bool UpdateKosher(EfratProject.ServiceReference2.kosher kosh) {
            return base.Channel.UpdateKosher(kosh);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateKosherAsync(EfratProject.ServiceReference2.kosher kosh) {
            return base.Channel.UpdateKosherAsync(kosh);
        }
        
        public bool AddProduct(EfratProject.ServiceReference2.BlProduct p) {
            return base.Channel.AddProduct(p);
        }
        
        public System.Threading.Tasks.Task<bool> AddProductAsync(EfratProject.ServiceReference2.BlProduct p) {
            return base.Channel.AddProductAsync(p);
        }
        
        public System.Collections.Generic.List<EfratProject.ServiceReference2.BlProduct> GetProducts() {
            return base.Channel.GetProducts();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<EfratProject.ServiceReference2.BlProduct>> GetProductsAsync() {
            return base.Channel.GetProductsAsync();
        }
        
        public System.Collections.Generic.List<EfratProject.ServiceReference2.kosher> GetKosher() {
            return base.Channel.GetKosher();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<EfratProject.ServiceReference2.kosher>> GetKosherAsync() {
            return base.Channel.GetKosherAsync();
        }
        
        public bool AddKosher(EfratProject.ServiceReference2.kosher k) {
            return base.Channel.AddKosher(k);
        }
        
        public System.Threading.Tasks.Task<bool> AddKosherAsync(EfratProject.ServiceReference2.kosher k) {
            return base.Channel.AddKosherAsync(k);
        }
        
        public System.Collections.Generic.List<EfratProject.ServiceReference2.kategor> GetKategor() {
            return base.Channel.GetKategor();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<EfratProject.ServiceReference2.kategor>> GetKategorAsync() {
            return base.Channel.GetKategorAsync();
        }
        
        public System.Collections.Generic.List<EfratProject.ServiceReference2.Inviting> GetInviting() {
            return base.Channel.GetInviting();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<EfratProject.ServiceReference2.Inviting>> GetInvitingAsync() {
            return base.Channel.GetInvitingAsync();
        }
        
        public bool AddCity(EfratProject.ServiceReference2.Cities c) {
            return base.Channel.AddCity(c);
        }
        
        public System.Threading.Tasks.Task<bool> AddCityAsync(EfratProject.ServiceReference2.Cities c) {
            return base.Channel.AddCityAsync(c);
        }
        
        public bool deleteproduct(EfratProject.ServiceReference2.BlProduct p) {
            return base.Channel.deleteproduct(p);
        }
        
        public System.Threading.Tasks.Task<bool> deleteproductAsync(EfratProject.ServiceReference2.BlProduct p) {
            return base.Channel.deleteproductAsync(p);
        }
        
        public bool deleteCity(EfratProject.ServiceReference2.Cities c) {
            return base.Channel.deleteCity(c);
        }
        
        public System.Threading.Tasks.Task<bool> deleteCityAsync(EfratProject.ServiceReference2.Cities c) {
            return base.Channel.deleteCityAsync(c);
        }
        
        public bool deleteCustomer(EfratProject.ServiceReference2.customers c) {
            return base.Channel.deleteCustomer(c);
        }
        
        public System.Threading.Tasks.Task<bool> deleteCustomerAsync(EfratProject.ServiceReference2.customers c) {
            return base.Channel.deleteCustomerAsync(c);
        }
        
        public bool deleteKosher(EfratProject.ServiceReference2.kosher kosh) {
            return base.Channel.deleteKosher(kosh);
        }
        
        public System.Threading.Tasks.Task<bool> deleteKosherAsync(EfratProject.ServiceReference2.kosher kosh) {
            return base.Channel.deleteKosherAsync(kosh);
        }
        
        public bool deleteHazmana(EfratProject.ServiceReference2.Inviting I) {
            return base.Channel.deleteHazmana(I);
        }
        
        public System.Threading.Tasks.Task<bool> deleteHazmanaAsync(EfratProject.ServiceReference2.Inviting I) {
            return base.Channel.deleteHazmanaAsync(I);
        }
        
        public byte[] GetImage(string fileName) {
            return base.Channel.GetImage(fileName);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetImageAsync(string fileName) {
            return base.Channel.GetImageAsync(fileName);
        }
        
        public void SaveImage(byte[] imageArray, string fileName) {
            base.Channel.SaveImage(imageArray, fileName);
        }
        
        public System.Threading.Tasks.Task SaveImageAsync(byte[] imageArray, string fileName) {
            return base.Channel.SaveImageAsync(imageArray, fileName);
        }
        
        public bool CreateOrder(EfratProject.ServiceReference2.Inviting invite, System.Collections.Generic.List<EfratProject.ServiceReference2.hazmana> LProducts) {
            return base.Channel.CreateOrder(invite, LProducts);
        }
        
        public System.Threading.Tasks.Task<bool> CreateOrderAsync(EfratProject.ServiceReference2.Inviting invite, System.Collections.Generic.List<EfratProject.ServiceReference2.hazmana> LProducts) {
            return base.Channel.CreateOrderAsync(invite, LProducts);
        }
        
        public System.Collections.Generic.List<EfratProject.ServiceReference2.BlProduct> SearchProducts(string P) {
            return base.Channel.SearchProducts(P);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<EfratProject.ServiceReference2.BlProduct>> SearchProductsAsync(string P) {
            return base.Channel.SearchProductsAsync(P);
        }
        
        public System.Collections.Generic.List<EfratProject.ServiceReference2.BlProduct> GetproductBychoose(EfratProject.ServiceReference2.kategor w) {
            return base.Channel.GetproductBychoose(w);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<EfratProject.ServiceReference2.BlProduct>> GetproductBychooseAsync(EfratProject.ServiceReference2.kategor w) {
            return base.Channel.GetproductBychooseAsync(w);
        }
        
        public System.Collections.Generic.List<EfratProject.ServiceReference2.hazmana> GetItemsinOrder() {
            return base.Channel.GetItemsinOrder();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<EfratProject.ServiceReference2.hazmana>> GetItemsinOrderAsync() {
            return base.Channel.GetItemsinOrderAsync();
        }
        
        public bool RemoveProductFromInvite(EfratProject.ServiceReference2.hazmana p) {
            return base.Channel.RemoveProductFromInvite(p);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveProductFromInviteAsync(EfratProject.ServiceReference2.hazmana p) {
            return base.Channel.RemoveProductFromInviteAsync(p);
        }
        
        public System.Collections.Generic.List<EfratProject.ServiceReference2.Inviting> GetOrdersByCity(int code) {
            return base.Channel.GetOrdersByCity(code);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<EfratProject.ServiceReference2.Inviting>> GetOrdersByCityAsync(int code) {
            return base.Channel.GetOrdersByCityAsync(code);
        }
        
        public System.Collections.Generic.List<EfratProject.ServiceReference2.Inviting> GetOrdersByDay() {
            return base.Channel.GetOrdersByDay();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<EfratProject.ServiceReference2.Inviting>> GetOrdersByDayAsync() {
            return base.Channel.GetOrdersByDayAsync();
        }
    }
}
