//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hazmana
    {
        public int HazmanaCode { get; set; }
        public int ProductCode { get; set; }
        public double Amount { get; set; }
        public bool sent { get; set; }
    
        public virtual inviting inviting { get; set; }
        public virtual product product { get; set; }
    }
}
