//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class inviting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inviting()
        {
            this.Hazmanas = new HashSet<Hazmana>();
        }
    
        public int HazmanaCode { get; set; }
        public int CodeCustomer { get; set; }
        public System.DateTime dateBuy { get; set; }
        public System.DateTime dateSent { get; set; }
        public bool sent { get; set; }
        public Nullable<double> filnalPrice { get; set; }
        public string notes { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hazmana> Hazmanas { get; set; }
    }
}
