//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerProject.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EfratDBEntities : DbContext
    {
        public EfratDBEntities()
            : base("name=EfratDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Hazmana> Hazmanas { get; set; }
        public virtual DbSet<inviting> invitings { get; set; }
        public virtual DbSet<Kategor> Kategors { get; set; }
        public virtual DbSet<Kosher> Koshers { get; set; }
        public virtual DbSet<product> products { get; set; }
    }
}
