//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.Hazmanas = new HashSet<Hazmana>();
        }
    
        public int ProductCode { get; set; }
        public string ProductName { get; set; }
        public double price { get; set; }
        public string ProductPicture { get; set; }
        public int KosherCode { get; set; }
        public bool tari { get; set; }
        public int KategorCode { get; set; }
        public Nullable<double> AmountIn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hazmana> Hazmanas { get; set; }
        public virtual Kategor Kategor { get; set; }
        public virtual Kosher Kosher { get; set; }
    }
}
